services:
  app:
    image: gen4:rce
    container_name: gen4rce-exploit
    dns:
      - 8.8.8.8
    volumes:
      - ./server:/home/server
      - ./project:/home/project
      - ./assets:/home/assets
    environment:
      HOST_IP_ADDRESS: ${HOST_IP_ADDRESS}
    tty: true
    working_dir: /home
    networks:
      - backend
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
  dnsmasq:
    container_name: dnsmasq
    image: strm/dnsmasq
    restart: always
    volumes:
      - ./configs/wfc.conf:/etc/dnsmasq.d/wfc.conf
    cap_add:
      - NET_ADMIN
    networks:
      - backend
    ports:
      - "53:53/tcp"
      - "53:53/udp"
  pkmn-server:
    image: pkmn-server-no-classic:0.0.1 #pkmn-wfc-server-pkmn-server:latest
    container_name: pkmn-server
    networks:
      - backend
    volumes:
      - ./assets/dlc/:/var/www/dwc_network_server_emulator/dlc/external/
    ports:
      - "443:443/tcp"
      - "8000:8000/tcp"
      - "9000:9000/tcp"
      - "9001:9001/tcp"
      - "9009:9009/tcp"
      - "9002:9002/tcp"
      - "9003:9003/tcp"
      - "9998:9998/tcp"
      - "27500:27500/tcp"
      - "27900:27900/tcp"
      - "27901:27901/tcp"
      - "28910:28910/tcp"
      - "29900:29900/tcp"
      - "29901:29901/tcp"
      - "29920:29920/tcp"
networks:
  backend:
    driver: bridge