out_of_packets_timeout: 5
packets:
  - packet_type: code
    filepath: "/home/project/out/diamond_pearl/communication/bin/communication.bin"

  - packet_type: data
    address: 0x23AB000
    filepath: "/home/assets/bins_out/boxname_writer_hgss_chunk_0.bin"
  
  - packet_type: code
    filepath: "/home/project/out/diamond_pearl/assembly_projects/bin/install_boxname_writer.bin"
