events {}

http {
    # Default server: catch-all for your exploit app
    server {
        listen 80 default_server;
        server_name gamestats2.gs.nintendowifi.net;

        location / {
            proxy_pass http://gen4rce-exploit:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Specific server for Nintendo game traffic
    server {
        listen 80;
        server_name localhost *.nintendowifi.net *.gs.nintendowifi.net;

        location / {
            proxy_pass http://pkmn-server:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}